#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop remote-relay-server.service >/dev/null 2>&1 || true
            if [ "$1" = "remove" ]; then
                systemctl disable remote-relay-server.service >/dev/null 2>&1 || true
            fi
        fi
        ;;
esac

exit 0
